// node-redis v4/v5 uses camelCase method names that map to Redis commands.
// We cover the same set as ioredis but mapped through the camelCase helper.
export const REDIS_COMMAND_NAMES = [
  'APPEND','AUTH','BGREWRITEAOF','BGSAVE','BITCOUNT','BITFIELD','BITFIELD_RO','BITOP','BITPOS',
  'BLMOVE','BLMPOP','BLPOP','BRPOP','BRPOPLPUSH','BZMPOP','BZPOPMAX','BZPOPMIN',
  'CLIENT','CLUSTER','COMMAND','CONFIG','COPY','DBSIZE','DEBUG','DECR','DECRBY','DEL','DISCARD','DUMP',
  'ECHO','EVAL','EVALSHA','EXEC','EXISTS','EXPIRE','EXPIREAT','EXPIRETIME',
  'FAILOVER','FCALL','FCALL_RO','FLUSHALL','FLUSHDB','FUNCTION',
  'GEOADD','GEODIST','GEOHASH','GEOPOS','GEORADIUS','GEORADIUS_RO','GEORADIUSBYMEMBER','GEORADIUSBYMEMBER_RO','GEOSEARCH','GEOSEARCHSTORE',
  'GET','GETBIT','GETDEL','GETEX','GETRANGE','GETSET',
  'HDEL','HELLO','HEXISTS','HGET','HGETALL','HINCRBY','HINCRBYFLOAT','HKEYS','HLEN','HMGET','HMSET','HRANDFIELD','HSCAN','HSET','HSETNX','HSTRLEN','HVALS',
  'INCR','INCRBY','INCRBYFLOAT','INFO',
  'KEYS','LASTSAVE','LATENCY','LCS','LINDEX','LINSERT','LLEN','LMOVE','LMPOP','LOLWUT',
  'LPOP','LPOS','LPUSH','LPUSHX','LRANGE','LREM','LSET','LTRIM',
  'MEMORY','MGET','MIGRATE','MONITOR','MOVE','MSET','MSETNX','MULTI',
  'OBJECT','PERSIST','PEXPIRE','PEXPIREAT','PEXPIRETIME',
  'PFADD','PFCOUNT','PFMERGE',
  'PING','PSETEX','PSUBSCRIBE','PSYNC','PTTL','PUBLISH','PUBSUB','PUNSUBSCRIBE',
  'QUIT','RANDOMKEY','READONLY','READWRITE','RENAME','RENAMENX','REPLICAOF','RESET','RESTORE','ROLE','RPOP','RPOPLPUSH','RPUSH','RPUSHX',
  'SADD','SAVE','SCAN','SCARD','SCRIPT','SDIFF','SDIFFSTORE','SELECT',
  'SET','SETBIT','SETEX','SETNX','SETRANGE','SHUTDOWN',
  'SINTER','SINTERCARD','SINTERSTORE','SISMEMBER','SLAVEOF','SLOWLOG',
  'SMEMBERS','SMISMEMBER','SMOVE','SORT','SORT_RO','SPOP','SPUBLISH','SRANDMEMBER','SREM','SSCAN','SSUBSCRIBE',
  'STRLEN','SUBSCRIBE','SUBSTR','SUNION','SUNIONSTORE','SUNSUBSCRIBE','SWAPDB','SYNC',
  'TIME','TOUCH','TTL','TYPE','UNLINK','UNSUBSCRIBE','UNWATCH',
  'WAIT','WATCH','XACK','XADD','XAUTOCLAIM','XCLAIM','XDEL','XGROUP','XINFO','XLEN','XPENDING','XRANGE','XREAD','XREADGROUP','XREVRANGE','XSETID','XTRIM',
  'ZADD','ZCARD','ZCOUNT','ZDIFF','ZDIFFSTORE','ZINCRBY','ZINTER','ZINTERCARD','ZINTERSTORE','ZLEXCOUNT',
  'ZMPOP','ZMSCORE','ZPOPMAX','ZPOPMIN','ZRANDMEMBER','ZRANGE','ZRANGEBYLEX','ZRANGEBYSCORE','ZRANGESTORE',
  'ZRANK','ZREM','ZREMRANGEBYLEX','ZREMRANGEBYRANK','ZREMRANGEBYSCORE','ZREVRANGE','ZREVRANGEBYLEX','ZREVRANGEBYSCORE','ZREVRANK',
  'ZSCAN','ZSCORE','ZUNION','ZUNIONSTORE',
] as const;

/** Convert "GETRANGE" → "getRange", "BITFIELD_RO" → "bitFieldRo", "SORT_RO" → "sortRo", "CLIENT SETNAME" variants handled via sendCommand. */
export const toCamelCase = (upper: string): string => {
  return upper
    .toLowerCase()
    .replace(/_([a-z])/g, (_, c) => c.toUpperCase())
    .replace(/([a-z])([a-z]+)/, (_m, a, b) => a + b); // keep first match lower
};
